### ISSUE TITLE
Instructions to use the xml parser in gnome desktop ubuntu 20.04

### ISSUE THREAD

**Issue by krishna2095** [Lin-Buo-Ren/libxml2-snap#2]
No instructions found in Read me file in repo

**Comment by brlin-tw** [comment]
This is a command-line interface only application, run the `snap info
_snap_name_` command in a terminal to verify what commands this snap
exposed to the system.

For the usage of the shipped commands please refer the upstream(libxml2)
documentation.

V Sai Krishna <notifications@github.com> 於 2020年12月29日 週二 下午1:12 寫道：
